---
name: CTest
on:
  push:
    branches:
      - main
    paths:
      - "libft/**"
      - "src/**"
  pull_request:
    paths:
      - "libft/**"
      - "src/**"
  workflow_dispatch:

jobs:
  ctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake g++

      - name: Initialize submodules
        run: git submodule update --init

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build --output-on-failure

