---
name: Norm
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  norm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: "libft/ include/ src/"