---
name: Norm
on:
  push:
    paths:
      - "libft/**"
      - "include/**"
      - "src/**"
  workflow_dispatch:

jobs:
  norm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: |
          pip install norminette==3.3.51
          norminette libft include src
