---
name: Norm
on:
  push:
    paths:
      - "libft/**"
      - "include/**"
      - "src/**"
  pull_request:
    paths:
      - "libft/**"
      - "include/**"
      - "src/**"
  workflow_dispatch:

jobs:
  norm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: "libft/ include/ src/"